### PR TITLE
Sieve approach

### PR DESCRIPTION
**Pull request by bobahop**
An approach for Sieve.

### CODE REVIEW

**Comment by bobahop** [comment]
@ErikSchierboom: C++ Sieve approach ready for review.

**Comment by siebenschlaefer** [comment]
Some small suggestions:

- The `std::vector` is named `composites`. *Personally* I'd rather use the name `sieve` because that's the eponymous Sieve of Eratosthenes. But naming is subjective and I can see why you chose `composites`.
- The function reserves a capacity of `limit / 2`. That's not wrong but are you sure that's worth the effort? Even for moderately large limits the number of primes is much smaller that `limit / 2`. If you really want to avoid any resize operation you could use one or multiple of the inequalities that the Wikipedia lists as [Approximations for the nth prime number](https://en.wikipedia.org/wiki/Prime_number_theorem#Approximations_for_the_nth_prime_number) or [Non-asymptotic bounds on the prime-counting function](https://en.wikipedia.org/wiki/Prime_number_theorem#Non-asymptotic_bounds_on_the_prime-counting_function). But *personally* I would omit the `reserve()` completely. All `std::vector` operations increase the capacity by some factor between 1.5 and 2, guaranteeing an amortized linear runtime and it's an optimization beyond the level of explanation.
- The inner `for` loop marks all composites of the current prime, starting with `number + number`. But you can choose a larger starting point: `number * number` because all multiples below that have been marked in a previous iteration. With this small optimization the runtime complexity becomes Θ(n log log n) (see [The Genuine Sieve of Eratosthenes](https://web.archive.org/web/20130514030554/http://www.cs.tufts.edu/~nr/comp150fp/archive/melissa-oneill/Sieve-JFP.pdf) by Melissa O'Neill).

In the explanation:

- "the number being iterated" -> "the current `number`", because it's a little bit simpler

**Comment by bobahop** [comment]
@siebenschlaefer: Thank you again for your comprehensive feedback! As mentioned in the forum, we're looking for optimistic merging for these. I encourage you to bring your expertise to improving them after merging. However, if these are too far below an acceptable quality level, I won't take offense if you prefer I not do them for C++. I admittedly have limited stamina for some details, especially after the burnout of having done so many for so many languages already. Thanks again!

**Comment by siebenschlaefer** [comment]
Sorry, it seems I misunderstood "ready for review".  
If you prefer merging it first and then improving it through PRs that's fine with me.

And no, I do not think the code or explanation is unacceptable.
The code is easy to read, idiomatic, and reasonably efficient, I had no problems understanding the explanation.

**Review by ErikSchierboom — APPROVED** [review]

**Comment by bobahop** [comment]
I'm okay with leaving it as is, but re starting with number + number, when we're processing `2`, if we don't set `4` to true for being a composite, won't it get skipped? As processing `3` won't handle it, and then when we iterate to `4` it will be false for being a composite and will be added to the primes. But math isn't my forte, so maybe I'm not seeing something?

**Comment by bobahop** [comment]
@ErikSchierboom or @siebenschlaefer: I think this might be ready to be merged now?

**Comment by ErikSchierboom** [comment]
@siebenschlaefer Any objections to merging this as is and improving things in a follow-up PR?

**Comment by bobahop** [comment]
Okay, I'm thinking the number _times_ itself would be more performant and would work. Let me make that change...

**Comment by siebenschlaefer** [comment]
Looks good!

**Comment by ErikSchierboom** [comment]
Thanks both!

**Pull request merged**
