### PR TITLE
Add more test cases in the sieve exercise

### PR DESCRIPTION
**Pull request by HenryRLee**
When the `limit` is a prime number, test if the answer includes the `limit`.

### CODE REVIEW

**Comment by HenryRLee** [comment]
I found that some students' solutions fail to include the `limit` in their answer when the `limit` is a prime number, hence the PR.

**Comment by patricksjackson** [comment]
The canonical test cases were changed quite a while ago to include that test actually, so this really only happened because we are behind on the test version. Can I ask instead that you add a few more tests to get us fully updated to the new spec?

The test suite is here: https://github.com/exercism/problem-specifications/blob/master/exercises/sieve/canonical-data.json

**Comment by HenryRLee** [comment]
@patricksjackson Sure thing. I just updated my PR.

**Comment by patricksjackson** [comment]
Ah sorry, could you make the order the same as the problem spec? So that it checks up to 1 , then 2, then 10, then 1000? That just makes a lot more sense from the perspective of the student.

Everything else looks fine, just do the reorder (making sure to keep the EXERCISM_RUN_ALL_TESTS thing after the new first test) and it'll be good to go.

**Comment by HenryRLee** [comment]
Sure! Fixed it.

**Comment by patricksjackson** [comment]
Awesome. Thanks!

**Pull request merged**
