### PR TITLE
#638 synced about.ms and introduction.md respectively

### PR DESCRIPTION
**Pull request by tesarect**
Updated about.md and exercises introduction.md with respect to numbers introduction.md file.

### CODE REVIEW

**Comment by vaeng** [comment]
Something seems very broken. Do you mind to do a new - clean pull request to see what all the checks are complaining about?

**Comment by tesarect** [comment]
sure, will do.

**Comment by tesarect** [comment]
@vaeng , created new PR as said. May i know how to delete this conflicted PR.

**Comment by vaeng** [comment]
I'm not sure you can as a non-maintainer. I'll do it and re-open the other one

**Pull request closed without merging**
