### PR TITLE
fix(catch): Update Catch2 to the latest version (#432)

### LINKED ISSUE #432: Catch2 v2.7.0 breaks on Apple Silicon
Hello exercism,
I am an utter beginner in C++ which is why I decided to go through that CPP track. Shortly after starting it, I got stuck at `hello-world`.

# Problem
All practices for the cpp track run fine so far on my PC. However, that is not the case for my M1 MacBook Air when using Apple Clang and CLion. Instead, it throws errors as shown in the log below: 

```log
====================[ Build | hello-world | Debug ]=============================
"/Users/pr1metine/Library/Application Support/JetBrains/Toolbox/apps/CLion-ARM/ch-0/203.7148.70/CLion.app/Contents/bin/cmake/mac/bin/cmake" --build /Users/pr1metine/projects/Exercism/cpp/hello-world --target hello-world -- -j 6
[ 25%] Building CXX object CMakeFiles/hello-world.dir/test/tests-main.cpp.o
In file included from /Users/pr1metine/projects/Exercism/cpp/hello-world/test/tests-main.cpp:2:
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6317:13: error: invalid token in expression
            CATCH_BREAK_INTO_DEBUGGER();
            ^
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6035:79: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() []{ if( Catch::isDebuggerActive() ) { CATCH_TRAP(); } }()
                                                                              ^
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6014:34: note: expanded from macro 'CATCH_TRAP'
    #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
                                 ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
In file included from /Users/pr1metine/projects/Exercism/cpp/hello-world/test/tests-main.cpp:2:
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6317:13: error: invalid operand
            CATCH_BREAK_INTO_DEBUGGER();
            ^
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6035:79: note: expanded from macro 'CATCH_BREAK_INTO_DEBUGGER'
    #define CATCH_BREAK_INTO_DEBUGGER() []{ if( Catch::isDebuggerActive() ) { CATCH_TRAP(); } }()
                                                                              ^
/Users/pr1metine/projects/Exercism/cpp/hello-world/test/catch.hpp:6014:34: note: expanded from macro 'CATCH_TRAP'
    #define CATCH_TRAP() __asm__("int $3\n" : : ) /* NOLINT */
                                 ^
<inline asm>:1:6: note: instantiated into assembly here
        int $3
            ^
2 errors generated.
make[3]: *** [CMakeFiles/hello-world.dir/test/tests-main.cpp.o] Error 1
make[2]: *** [CMakeFiles/hello-world.dir/all] Error 2
make[1]: *** [CMakeFiles/hello-world.dir/rule] Error 2
make: *** [hello-world] Error 2
```

# Fix
Luckily, I was able to fix this issue by bumping `Catch2` to the latest version (i. e. overwrite `test/catch.hpp` with [Catch2 v2.13.4](https://github.com/catchorg/Catch2/releases/download/v2.13.4/catch.hpp)). Thus, bumping all occurrences of `catch.hpp` will likely resolve this.

### PR DESCRIPTION
**Pull request by pr1metine**
Fixes #432. Because I did not know of a smarter alternative, I had to replace all `catch.hpp` by hand. Furthermore, I only tested the changes on `hello-world` and on my M1 Mac.

### CODE REVIEW

**Comment by patricksjackson** [comment]
1. Yes, this is what's necessary to update Catch. Thanks.
2. I need to fix our CI before I can test this and merge. The Configlet linter that checks the track config files is showing we have some errors, which breaks our CI entirely. And that check is a prerequisite for executing the actual tests. It was setup this way assuming that the Configlet linter check wouldn't change and break existing code.

**Comment by pr1metine** [comment]
After a quick google search, I found [an easy way](https://www.unix.com/unix-for-dummies-questions-and-answers/71534-replace-all-files-certain-filename-another-file.html) to update Catch2:

```bash
find . -name catch.hpp |\
while read filename
do
     cp /path/to/new_catch.hpp $filename
done
```

**Comment by pr1metine** [comment]
Any updates?

**Comment by iHiD** [comment]
@pr1metine Thanks for this work and sorry for the slow responses! 
@patricksjackson It seems that the CI now works (although configlet fails), so maybe I can merge this using my admin rights?

**Comment by pr1metine** [comment]
Better late than never haha

**Review by patricksjackson — APPROVED** [review]

**Comment by patricksjackson** [comment]
Done. Thanks!

**Pull request merged**
