### PR TITLE
Added Accumulate exercise with all necessary implementation

### PR DESCRIPTION
**Pull request by IsaacFung**

### CODE REVIEW

**Comment by IsaacFung** [comment]
Will resolve checks that were not successful.

**Comment by siebenschlaefer** [comment]
- According to the tests `accumulate()` should return a `std::string`, but the example returns a `std::vector`. I think the example is right.
- `accumulate()` takes an OUT parameter *and* returns a result. IMHO the OUT parameter is unnecessary and can be removed.  

- There are four tests initially enabled. Exercism practices a TDD approach where initially only the first test is enabled.  
- The disabled tests are from the "Acronym" exercise.  

---

- The instructions are in a file`description.md`. In  the other C++ exercises that file is named `README.md`.  
- The instructions describe the task in the sections "Accumulate" *and* "Passing the Tests". In the other exercises "Passing the Tests" just describes Exercism's TDD approach.  
- The instructions do not contain the sections "Source" and "Submitting Incomplete Solutions".  

---

- The instructions contain the sentences "*You will need to write functions that perform some of these operations yourself since you are not allowed to use any additional libraries except for vector.*" and "*Do this without including any additional libraries except for \<vector\>.*" But in the [original description](https://github.com/exercism/problem-specifications/blob/master/exercises/accumulate/description.md) only functional tools like "*collect/map/fmap/whatchamacallit*" are forbidden. IMHO forbidding `std::sqrt()` changes the scope of this exercise.
- In the [original task](https://github.com/exercism/problem-specifications/blob/master/exercises/accumulate/description.md) a function is passed, not a string that acts as an ID for some predefined functions. IMHO the C++ translation should do that, too. Either pass a `std::function` or make `accumulate` a templated function that accepts any callable. *Personally* I would prefer the latter.

**Comment by siebenschlaefer** [comment]
The problem specification repository does not contain tests. I looked what tests other language tracks do:
- [Python](https://github.com/exercism/python/blob/66b9e40115172daefcf3f6eb6d2e4fe0171ae60a/exercises/accumulate/accumulate_test.py): empty array, various functions (pow, divmod, capitalize), nesting
- [Perl6](https://github.com/exercism/perl6/blob/545361343b4788089e659c3d085388899626483d/exercises/accumulate/accumulate.t): empty array, various functions (square, divmod, capitalize string, reverse string), nesting
- [PHP](https://github.com/exercism/php/blob/cd1ffbe140ee0a3c8375dbd7710f242c808affe1/exercises/accumulate/accumulate_test.php): empty array, various functions (square, uppercase, reverse string, to constant), nesting, builtin functions, static method, invoke, object and array notation (?)
- [JavaScript](https://github.com/exercism/javascript/blob/189a99767ebe2271eff2b4a784539cec9334dea5/exercises/accumulate/accumulate.spec.js): empty array, various functions (square, uppercase, reverse string), nesting
- [Coffeescript](https://github.com/exercism/coffeescript/blob/405d50a0fb0b8cce35714b0e286c422de6caa72f/exercises/accumulate/accumulate_test.spec.coffee): empty array, various functions (square, uppercase, reverse string), nesting
- [Swift](https://github.com/exercism/swift/blob/ce9509e301f0661b0e9758f5cef23edd1d1bb50e/exercises/accumulate/Tests/AccumulateTests/AccumulateTests.swift): empty array, various functions (square, uppercase, reverse string), nesting
- [Purescript](https://github.com/exercism/purescript/blob/0532d3d6f7bd9b1c854e4bb889251157a38bc4a2/exercises/accumulate/test/Main.purs): empty list, single element list, various functions (square, uppercase), different return type
- [Java](https://github.com/exercism/java/blob/a0f91066641f672d1d77b2a3f07df3732c9096b4/exercises/accumulate/src/test/java/AccumulateTest.java): empty list, various functions (square, uppercase, reverse string, nesting
- [Kotlin](https://github.com/exercism/kotlin/blob/8ff0649cada1c4824e52e75a385298f5d708bf5d/exercises/accumulate/src/test/kotlin/AccumulateTest.kt): empty list, various functions (square, uppercase, reverse string), nesting, different return type
- [C#](https://github.com/exercism/csharp/blob/c64e503a1f624eb133b0bf7bb99400b3da69db22/exercises/accumulate/AccumulateTest.cs): empty array, various functions (square, uppercase, reverse string), nesting, different return type
- [VB.net](https://github.com/exercism/vbnet/blob/cd2624931ce59c1ed435092090e57d619ea14e6b/exercises/accumulate/AccumulateTest.vb): empty array, various functions (square, uppercase, reverse string), nesting, lazy evaluation
- [Go](https://github.com/exercism/go/blob/d09895404e5b08dbdca8222ca7e01d4687e422e1/exercises/accumulate/accumulate_test.go): empty list, various functions (square, uppercase, reverse string)
- [Haskell](https://github.com/exercism/haskell/blob/47a423fd6e3d7438e0a1c22d68c052e95a1122a8/exercises/accumulate/test/Tests.hs): empty iist, various functions (square, uppercase, reverse string), nesting, lazy evaluation
- [Elixir](https://github.com/exercism/elixir/blob/6ce0f51d32037fad61eaed451edfedba564bf71e/exercises/accumulate/test/accumulate_test.exs): empty iist, various functions (square, uppercase, reverse string), nesting
- [F#](https://github.com/exercism/fsharp/blob/8f7116e5c3fab1385cf756da57444a42d99167a0/exercises/accumulate/AccumulateTest.fs): empty iist, identity, various functions (square, uppercase, reverse string), nesting
- [Scala](https://github.com/exercism/scala/blob/b23b9e01694d11c5428ec939a4ca022503fb072f/exercises/accumulate/src/test/scala/AccumulateTest.scala):  empty list, various functions (square, uppercase, reverse string), different return type
- [Clojure](https://github.com/exercism/clojure/blob/2323a262860425d530c71fe3f1b1ca22a75f51bd/exercises/accumulate/test/accumulate_test.clj): empty iist, various functions (square, uppercase, reverse string), nesting
- [Racket](https://github.com/exercism/racket/blob/daaef6b1623fdd15f2a21bbd3cb277341004a08e/exercises/accumulate/accumulate-test.rkt): empty list, various functions (square, uppercase, reverse string)
- [Erlang](https://github.com/exercism/erlang/blob/9ca93b1ddec0c26b518310c3a99c79dac06c068e/exercises/accumulate/test/accumulate_tests.erl): various functions (square, uppercase, reverse string), nesting
- [SML](https://github.com/exercism/sml/blob/7505306d837802caaadaf7cb760e09fbd01f83c7/exercises/accumulate/test.sml): empty list, various functions(identity, square, cube, increment, decrement)
- [LFE](https://github.com/exercism/lfe/blob/master/exercises/accumulate/test/accumulate-tests.lfe): various functions (square, uppercase, reverse string), nesting

**Comment by siebenschlaefer** [comment]
IMHO accumulate should take a function as argument, not a `std::string` that acts as an ID for some predefined functions.  
But should we use a regular function that takes and returns a `std::vector<int>`? Or should we use a templated function? And how much metaprogramming do we expect from our students? That also affects the tests: Do we only test `int` -> `int` transformations? Or `T` -> `T` transformations (for a generic type `T`)? Or do we want `T1` -> `T2` transformations (for generic types `T1` and `T2`)? Do we only pass traditional functions? Or possibly stateful lambdas? Or any callables?

These are some possible declarations:
```cpp
std::vector<int> accumulate(const std::vector<int>& original, int (*f)(int));   // 1

std::vector<int> accumulate(const std::vector<int>& original, std::function<int(int)> f);   // 2

template <typename T>
std::vector<T> accumulate(const std::vector<T>& original, std::function<T(T)> f);
template <typename T>
std::vector<T> accumulate(const std::vector<T>& original, T (*f)(T));   // 3

template <typename T1, typename T2>
std::vector<T2> accumulate(const std::vector<T1>& original, std::function<T2(T1)> f);
template <typename T1, typename T2>
std::vector<T2> accumulate(const std::vector<T1>& original, T2 (*f)(T1));   // 4

template <typename T1, typename T2, typename UnaryFunction>
std::vector<T2> accumulate(const std::vector<T1>& original, UnaryFunction f);   // 5

template <typename T1, typename UnaryFunction>
auto accumulate(const std::vector<T1>& original, UnaryFunction f)
    -> std::vector<decltype(f(*std::begin(original)))>;   // 6

template <typename Range, typename UnaryFunction>
auto accumulate(const Range& original, UnaryFunction f)
    -> std::vector<decltype(f(*std::begin(original)))>;   // 7
```

*Personally* I would choose 5, 6, or 7. But we should keep in mind that we should be able to mentor this exercise. I think the choices are hard.

**Comment by IsaacFung** [comment]
Will definitely make an updated revision soon. Definitely appreciate the feedback.

**Comment by patricksjackson** [comment]
I will probably be against merging this.

I would _strongly_ suggest that you instead implement a different exercise with the tests specified in the problem-specifications repo, I only vaguely recall that problems without test suites even existed.

We don't have the manpower to maintain test suites to the standards they should be, and the people active in the problem-specifications repo are very used to doing this. It's a central place where they can help put together a logical progression of tests and share that knowledge across the languages.

**Comment by IsaacFung** [comment]
I have begun pivoting towards implementing the change exercise instead and have completed almost all of the current test suite. I will revisit accumulate after finishing that.

**Comment by patricksjackson** [comment]
I'm closing this PR for now. Feel free to open another one if you finish making your changes.

**Pull request closed without merging**
