### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by pdmoore**
Fix typos in the Assignment Operators section.

### CODE REVIEW

**Review by siebenschlaefer — APPROVED** [review]
LGTM.

I think this whole text sounds and looks a little bit odd ("add a value *over* the existing value", "assigns a variable *with* a literal", "operators modifies", inconsistent commas) and could use some care from a native English speaker.

**Comment by pdmoore** [comment]
Thanks for the quick turnaround on this!
Agreed on the revamp. I wanted to separate the simple fix from a larger change. I think there should be mention of operations in parentheses taking precedence over left-to-right order. The solution also seems to require std:ceil but doesn't cover floor vs ceiling rounding.
This exercise also explains using an apostrophe to separate digits which would have been better placed in an earlier exercise in the syllabus, Last Will, which uses that notation without any mention of it.

**Review by vaeng — APPROVED** [review]
Thanks for the corrections! 🥳

**Comment by vaeng** [comment]
> Thanks for the quick turnaround on this!

Thanks for opening a PR!


> Agreed on the revamp. I wanted to separate the simple fix from a larger change. I think there should be mention of operations in parentheses taking precedence over left-to-right order. The solution also seems to require std:ceil but doesn't cover floor vs ceiling rounding.

I merged the fixes for the typo, there might be other places that have the same texts, I will try to correct those as well. Generally there is the introduction from the concept, which is reused in the about and again in each exercise that uses the concept. Three times the work. I would be happy to automate that bit with templates.

> This exercise also explains using an apostrophe to separate digits which would have been better placed in an earlier exercise in the syllabus, Last Will, which uses that notation without any mention of it.

Good point. I was sure I had those in the right order, I have to check the config.json if there was a mix-up somewhere.

**Comment by pdmoore** [comment]
> I merged the fixes for the typo, there might be other places that have the same texts, I will try to correct those as well.

I wasn't aware of the duplication - will keep it in mind for the future.

For this particular set of typos they also need fixing in:
exercises/concept/freelancer-rates/.docs/introduction.md
./concepts/numbers/about.md

**Pull request merged**
