### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by jonfoocy**
Add missing `string` keyword to example

### CODE REVIEW

**Comment by vaeng** [comment]
Thanks for catching this!

**Comment by vaeng** [comment]
Will reopen. Ping me next time, so I can see it.

**Comment by vaeng** [comment]
The branch has been deleted, I cannot reopen it :/

**Comment by jonfoocy** [comment]
Restored the branch!

**Review by vaeng — APPROVED** [review]

**Pull request merged**
