### PR TITLE
[Concept Exercises]: Small Formatting, Typo, & Link Fixes

### PR DESCRIPTION
**Pull request by BethanyG**
Did a pass through all the markdown docs for the concept exercises:

- [x] Ran Prettier
- [x] Looked for spelling errors/typos
- [x] Reviewed Reference Link formatting
- [x] Double-checked admonition formatting after prettier formatting

### CODE REVIEW

**Comment by BethanyG** [comment]
The vast bulk of these were removal or addition of white space.  Most links were fine, and there were only two stray typos.

**Comment by siebenschlaefer** [comment]
LGTM. (the "speficic" looks like one of my typos, i'm glad i'm not alone)

Do we use the British or American spelling of "initialization"?

**Review by siebenschlaefer — APPROVED** [review]

**Comment by BethanyG** [comment]
Allegedly American. But as an American, I can say that I often can't see the difference. 😂   So I probably missed that one!!

And the only reason I caught "speficic" is because my editor highlighted it....my brain has learned and embedded the incorrect spelling there, and there is nothing I can do about it. 😆

**Comment by BethanyG** [comment]
Going to push the big green button on this so that I can pull these changes down and do a sweep of the newer practice exercises.

**Pull request merged**
