### PR TITLE
Implement Binary Conversion

### PR DESCRIPTION
**Pull request by Piboons**
Binary Conversion Implemented

(One of my first GitHub Contributions, sorry if I did some mistakes!)

### CODE REVIEW

**Comment by NobbZ** [comment]
Hello @Piboons!

The files you have edited are meant to be stubs for students of the exercism.io platform to be downloaded as a shallow boilerplate to implement the exercise as described in the README. Along side we also have an example implementation to proof solvability of the exercise in the `example.{h,cpp}` which already contains a solution:

https://github.com/exercism/cpp/blob/master/exercises/binary/example.cpp

**Comment by siebenschlaefer** [comment]
Welcome to Exercism

If you want to practice your C++ feel invited to join the C++ track through the [Exercism website](http://exercism.io/). We currently have 52 exercises that challenge you to write a solution that passes the tests and you can submit your solution for mentoring.

This github repository is for the instructions, tests and the CMake files that are necessary to provide those challenges throught the Exercism website.

**Comment by Piboons** [comment]
Oh, sorry, I thought we had to submit our code by a Pull Request ! I'm going to delete this one and submit my code on [exercism.io](http://www.exercism.io), sorry for this mistake !

**Comment by patricksjackson** [comment]
No problem! This actually helps point out that our README could use an update anyways :)

**Pull request closed without merging**
