### PR TITLE
Update introduction.md

### PR DESCRIPTION
**Pull request by ilmoro93**
Corrected wrong vector declaration

### CODE REVIEW

**Review by siebenschlaefer — APPROVED** [review]
Good catch. Thank you!

**Review by vaeng — CHANGES_REQUESTED** [review]
Would you please also change this in the respective exercise?

**Comment by ilmoro93** [comment]
Corrected `introduction.md` in `making-the-grade`.

However in your comment when I click on [652b20d](https://github.com/exercism/cpp/commit/652b20daaab508e2169f8586583ddadd73d6bbe8) I see a change about `TEST_CASE("Alien is always hit", "[task_2]")`. Is this an error with the link?

> Would you please also change this in the respective exercise?
> 
> https://github.com/exercism/cpp/blob/652b20daaab508e2169f8586583ddadd73d6bbe8/exercises/concept/making-the-grade/.docs/introduction.md?plain=1#L31

**Comment by vaeng** [comment]
Woudl you please patch

> Is this an error with the link?

No, that's fine. I just grabbed the link for the line from another branch, sorry.

**Review by vaeng — APPROVED** [review]
Thanks for your time.

**Pull request merged**
