### PR TITLE
Update Exercism URL, add reference links

### PR DESCRIPTION
**Pull request by alexmitchelldev**
@vaeng noticed the URL was out of date so fixed this and added reference links.

### CODE REVIEW

**Review by siebenschlaefer — COMMENTED** [review]
LGTM, thank you!

Do you mind taking the opportunity to clean up the document a little bit by putting each sentence on a single line?

**Comment by alexmitchelldev** [comment]
Sure! Here you go :)

**Review by vaeng — APPROVED** [review]
Thanks

**Review by siebenschlaefer — APPROVED** [review]
LGTM, thank you.

**Pull request merged**
