### PR TITLE
Exercise levenshtein distance

### PR DESCRIPTION
**Pull request by marcelritzschke**
Hey! I want to add the levenshtein distance as new exercise to the category algorithms. I already opened a PR to the problem specifications repo (https://github.com/exercism/problem-specifications/pull/1634) .

### CODE REVIEW

**Comment by KevinWMatthews** [comment]
Hey @n4bla , thanks for submitting a new exercise!

I don't have time for a proper code review at this moment, but I would like to let you know that we see this and intend to take a deeper look. At first glance, I'm impressed with the quality of your submission - you seem to have a good understanding of the Exercism ecosystem!

I see that the `problem-specifications` repo might not be able to merge the exercise spec in the short term. Personally I don't see an issue with having an extra exercise (especially since you've laid the groundwork), though I welcome feedback from other maintainers and mentors.

**Comment by KevinWMatthews** [comment]
One question for mentors - what should this exercise be unlocked by?

**Comment by patricksjackson** [comment]
I won't have time to review (on a work trip now and will be on vacation for several weeks), but I did want to chime in.

I agree with @KevinWMatthews, I'm normally against changes here that differ from the problem-specifications repo but this is fairly clear a good exercise and will be added to problem-specifications when it makes sense. If I recall correctly, this is also one of the fundamental examples used to teach dynamic programming, so should be good if that topic comes up for v3.

Two suggestions from a quick look:
1. Add a longer description and a simple example to the README info. The wikipedia article does a pretty good job of this.
2. Raise the difficulty level, probably to 7. The code is pretty simple but the algorithm is very non-obvious if you don't already know it.

**Comment by siebenschlaefer** [comment]
> One question for mentors - what should this exercise be unlocked by?

Does it have to be a core exercise? Otherwise "hamming" would be a good candidate.

**Comment by KevinWMatthews** [comment]
@patricksjackson Thanks for the feedback! Enjoy your travels.

@siebenschlaefer This does not need to be a core exercise. The problem specifications repo may not be able to merge this exercise description for awhile, so it's probably best that we add this as an extra exercise - keep the core of the track in sync with other languages.

Hamming could make sense, but it looks like it is an extra exercise. I thought that only core exercises unlocked extra exercises. Is there a core exercise that this would follow well? Maybe `Raindrops`, `Pangram`, or `Reverse String`?

**Comment by siebenschlaefer** [comment]
> I thought that only core exercises unlocked extra exercises. 

That's what I wanted to know. Thanks for answering that anyway :-)

@n4bla What do you think will be common pitfalls or talking points? Besides the usual talking points like passing by reference to const and readable code I can think of using `std::iota()` and using to one-dimensional vectors (and swapping them) instead of a two-dimensional one.

**Comment by n4bla** [comment]
Hey, first I have to say: Thanks a lot for appreciating my work and giving helpful hints. I am relatively new to github and need to get a better overview, what is going on. Did not see that adding new exercises is blocked in the spec repo. 

@KevinWMatthews The readme files are a very good starting point to get into touch with ecosystem.
@patricksjackson I will work on the exercise description.

@siebenschlaefer I think the basic points would be :
1. proper declaring the vectors (what exactly do you mean with using two one-dimensional vectors and swapping them? This sounds interesting. In my example implementation I am using a two-dimensional one )
2. initializing the first row/column for what `std::iota()` can be used 
3. finding the minimum of three values

**Comment by patricksjackson** [comment]
Closing this, feel free to open a new PR if anyone wants to pick this up.

**Pull request closed without merging**
