### PR TITLE
#638 Synced about.md and exercises introduction.md with new introduction.md

### PR DESCRIPTION
**Pull request by tesarect**
Updated 
- concepts/numbers/about.md and 
- exercises/concept/freelancer-rates/.docs/introduction.md 
with concepts/numbers/introduction.md

### CODE REVIEW

**Comment by tesarect** [comment]
@vaeng , just a reminder on the review.

**Comment by vaeng** [comment]
Did you see my comment about the removed lines?

**Comment by tesarect** [comment]
Sorry @vaeng , I can't see any comments on the files changed.

**Comment by tesarect** [comment]
@vaeng, Sorry for the late reply. Was sick and took long enough to recover.


> Did you see my comment about the removed lines?

Regarding the comments, im unable to see any
image

**Comment by vaeng** [comment]
> @vaeng, Sorry for the late reply. Was sick and took long enough to recover.
> 
> > Did you see my comment about the removed lines?
> 
> Regarding the comments, im unable to see any 

You removed the casting section from the about.md file:

image

**Comment by tesarect** [comment]
Sorry, on my view/changes page, there is no comments visible(haven't received mail notification too).
> why did you remove the parts about casting and precision?
Since you mentioned "it is basically two files that need copy-pasting" on the initial comment under the issue, i thought it should be exact replica of the the numbers introduction file.

so can i retain the casting & precision part and initiate a new PR ?

**Comment by vaeng** [comment]
> Since you mentioned "it is basically two files that need copy-pasting"

Sorry, I wasn't precise here.

> so can i retain the casting & precision part and initiate a new PR ?

I would prefer if you would just add another commit to this PR

**Comment by tesarect** [comment]
@vaeng , i have added as per your comment.
Also, is there any access rights for comment visibility ? because, im unable to see the comments still, which lead me to an assumption that everything is fine.

**Comment by vaeng** [comment]
> Also, is there any access rights for comment visibility ? because, im unable to see the comments still, which lead me to an assumption that everything is fine.

Maybe you have to set yourself as the assigned person?

Also you should see the comments and reviews for anything, there are no closed visibility things for this kind of thing

**Review by vaeng — APPROVED** [review]
LGTM

**Pull request merged**
