### PR TITLE
Write "approaches" for reverse-string

### PR DESCRIPTION
**Pull request by siebenschlaefer**
Please feel free to critize anything, big-picture issue and small nitpicks.

### CODE REVIEW

**Comment by iHiD** [comment]
Thanks so much for this. @ErikSchierboom will take a look tomorrow!

**Review by ErikSchierboom — APPROVED** [review]
This is fantastic!

**Review by vaeng — APPROVED** [review]

**Comment by vaeng** [comment]
I really like the variety :)

**Comment by siebenschlaefer** [comment]
Should we merge (and correct any small things like typos later) or wait for other reviewers?

**Comment by siebenschlaefer** [comment]
If anybody wants to proof-read this, visit https://exercism.org/tracks/cpp/exercises/reverse-string/dig_deeper to see the rendered version.

**Pull request merged**
