### PR TITLE
C++ phone number test cases 

### PR DESCRIPTION
**Pull request by ViralTaco**
Added tests, fixed wrong test cases.  
I have no clue what I'm doing. I really hope this doesn't mess up anything.

### CODE REVIEW

**Comment by ViralTaco** [comment]
Ok so it fails on `#include <string>`
So… um… Keep the standard as `11` rather than `17` (current standard) in the CMake file? 

I'm not even sure it would pass the tests with C++11

To be clear it's the example that won't compile. 
Even though it compiles successfully with clang and g++-8 using the current standard. :/

**Comment by patricksjackson** [comment]
2 things before I can review this:

1. Please don't touch the travis and cmake settings, they are there for a reason. They are both setup to test compatibility with the oldest compilers we support. (I'm in the process of adding a more recent compiler to Travis as well, just haven't gotten around to merging it). There are a number of discussions around updating the CMake config to at least support a later version, but we need to continue to support people who don't have easy access to new compilers. Regardless, this isn't the place to discuss that.
2. You included a license statement despite that not being the convention here. This repo is MIT licensed but we don't have individual attributions in the files. If you require that attribution as part of your contribution I will need to go determine what we can do about it, since I am not the owner of any of the License info.

**Comment by ViralTaco** [comment]
> 2 things before I can review this:
> 
> 1. Please don't touch the travis and cmake settings, they are there for a reason. They are both setup to test compatibility with the oldest compilers we support. (I'm in the process of adding a more recent compiler to Travis as well, just haven't gotten around to merging it). There are a number of discussions around updating the CMake config to at least support a later version, but we need to continue to support people who don't have easy access to new compilers. Regardless, this isn't the place to discuss that.
> 2. You included a license statement despite that not being the convention here. This repo is MIT licensed but we don't have individual attributions in the files. If you require that attribution as part of your contribution I will need to go determine what we can do about it, since I am not the owner of any of the License info.

Ok 1 working on that right away. 
And 2 to be honest that's just my IDE snippet and I haven't removed it. 
I can remove it as long as it stays MIT license I have no problems with that.

**Comment by ViralTaco** [comment]
Added new line at the end of .travis.yml so github stops shouting about it

**Comment by KevinWMatthews** [comment]
Hey @ViralTaco ,

Thanks again for your help. You mentioned in #227 that it's your first contribution to exercism... welcome! Is this your first time contributing to an open source project, too?

First a high-level idea: as a general strategy it's best to split different concerns into separate pull requests. That typically allows your changes to be incorporated most quickly. As an example, something trivial to fix (a newline at the end of `travis.yml` could get held up because of something complex (the C++ standard or compiler version).

In this case, you've touched on four things: Travis, CMake, the unit tests, and the example solution. It could work but, as Patrick noted, it's easy to dip into deep waters unwittingly.

Are you willing to split these into separate requests? Personally, I'd like to see your new test suite run against the existing example. I'm quite curious to see if the new suite compiles/links/passes tests. If not, it would be super convenient to see precisely what error messages Travis spits out. Then we'll have a better frame of reference to update the tests and/or the example.

Your `travis.yml` newline fix should be an easy merge. I know it seems ridiculous to put it in a separate pull request, but if you do it's super easy to discuss and incorporate.

For CMake, take a look at #189 to see what we discussed the last time around.

Of course, we're happy to consider a new example solution too. I imagine that we'll prioritize the new test suite, however - this directly faces the end user. 

Cheers!

**Comment by ViralTaco** [comment]
> Hey @ViralTaco ,
> 
> Thanks again for your help. You mentioned in #227 that it's your first contribution to exercism... welcome! Is this your first time contributing to an open source project, too?

Yes, it is. And you're welcome. 

> First a high-level idea: as a general strategy it's best to split different concerns into separate pull requests. That typically allows your changes to be incorporated most quickly. As an example, something trivial to fix (a newline at the end of `travis.yml` could get held up because of something complex (the C++ standard or compiler version).
> 
> In this case, you've touched on four things: Travis, CMake, the unit tests, and the example solution. It could work but, as Patrick noted, it's easy to dip into deep waters unwittingly.

I don't know how I can undo that to be honest and I don't think a single newline character warrants 
spending more time on this. I've already spent at least 5 hours on this. And apparently it's worthless to all of you. 

So I'm thinking I should just give up. What do you think? 

You don't have to merge this pull request feel free to pick any part of the code you like and leave whatever you don't out. Just copy and paste. I don't care anymore. 

Cheers.

**Comment by ViralTaco** [comment]
Ok you know what, this is too much of a headache. Sorry for that. I'll close this this request and make 2 others based on what @KevinWMatthews asked. 
Please confirm… 2 pull requests:

1. The test cases
2. The examples

Right?

**Comment by KevinWMatthews** [comment]
Hi @ViralTaco , that sounds perfect.

I think you can do something like:
  * Copy your revised `phone_number_test.cpp`
  * Use `git checkout` to create a new branch from exercism's current master branch
  * Paste in your revised `phone_number_test.cpp`
  * Commit
  * Create a new merge request

It may not be perfect right away, but don't fret. We'll learn something from the error messages and patch it up from there.

Thanks for you willingness to help. Please do be patient with us as well - giving feedback to open source contributions is both an art and a skill that I'm still developing.

I look forward to seeing your work! If you get stuck, feel free to ask another question here. I hope to be back online in the morning, and others are around as well.

**Comment by ViralTaco** [comment]
I mean I really can't use git. 
Imma close this now… 
Thanks for the help

**Pull request closed without merging**
